- components/upload/asset.jsx
- pages/assets.jsx
- pages/upload/asset.jsx
Actualmente tiene datos estáticos. Issue #14
> feat: Añadida vista de listado de assets

- components/upload/asset.jsx
- components/upload/displayImage.jsx
- pages/assets/index.jsx
También se han borrado los imports no utilizados. Issue #18
> feat: Creado el fomulario para añadir nuevos assets

- components/auth/AlertMessage.js
- components/common/ThemeButton.jsx
- components/layout/Layout.jsx
- components/layout/Navbar.jsx
- package-lock.json
- package.json
- pages/login.jsx
- pages/signup.jsx
This PR adds the UI for the login and sign up pages. I still need to add the functionality. The files also repeat a lot of code, so it could be decomposed a little.
> [AUTH] Create sign up and login pages

- components/common/CenteredText.jsx
- components/layout/Navbar.jsx
- context/ApolloContext.jsx
- context/AuthContext.jsx
- lib/auth.js
- package-lock.json
- package.json
- pages/_app.js
- pages/confirmation.jsx
- pages/login.jsx
- pages/profile.jsx
- pages/signup.jsx
This PR adds the main functionality for the login and signup pages. It is still missing validation and some edge cases, but the main functionality should be done.
> [AUTH] Auth main functionality

- lib/auth.js
- pages/login.jsx
- pages/signup.jsx
This PR adds error validation to the login form and signup forms.
> [AUTH] add form validation to login page

- components/layout/Navbar.jsx
- context/ApolloContext.jsx
- lib/auth.js
- pages/login.jsx
- pages/profile.jsx
This PR refactors the authentication flow to be more consistent. It now uses the `useReducer` hook instead of a bunch of `useState` hooks.
> [AUTH] Refactor auth flow

- components/catalogue/NewProduct.jsx
- pages/index.jsx
Basic product creation. I will implement input validation in a future push
> Product creation

- components/catalogue/EditProduct.jsx
- components/catalogue/EditableProduct.jsx
- components/catalogue/ProductDetails.jsx
- pages/products/[id].jsx
Edit a single product implemented
> Edit products #47

- components/upload/Alert.js
- components/upload/UploadApi.js
- components/upload/asset.jsx
- pages/assets/[id].jsx
- pages/assets/index.jsx
Se ha integrado el listado de assets en front. Issue #19
> [Upload] Integración de listado de assets

- components/upload/UploadApi.js
- pages/assets/[id].jsx
- pages/assets/index.jsx
Si el usuario no está logueado, no puede acceder al listado. Si no existe el asset, se redirige a la página de catalog. Issue #20
> feat: Incorporación de restricciones de acceso a asset

- components/layout/Navbar.jsx
- components/upload/UploadApi.js
- pages/assets/[id].jsx
> Integración de los métodos de put y delete de back con el front

- components/auth/LoginForm.js
- components/auth/SignupForm.js
- components/auth/SocialButtons.js
- lib/firebase.js
- package-lock.json
- package.json
- pages/confirm/[token].js
- pages/confirm/index.js
This PR adds the option to login with google.
> [AUTH] Add social auth functionality

- components/auth/LoginForm.js
- components/auth/SignupForm.js
- components/auth/SocialButtons.js
- pages/confirm/[token].js
This PR quickly fixes the loading state in every mutation for the auth components. It also adds a loading state to the social auth.
> [AUTH] fix loading state

- components/upload/UploadApi.js
- pages/assets/[id].jsx
- pages/assets/index.jsx
Se ha integrado la llamada backend de la creación de asset. Issue #21
> feat: Integración de creación de asset

- components/auth/EmailForm.js
- components/auth/LoginForm.js
- components/auth/ResetPasswordForm.js
- components/auth/SignupForm.js
- components/auth/SocialButtons.js
- components/common/LoadingSpinner.jsx
- components/layout/Layout.jsx
- pages/confirm/[token].js
- pages/reset-password/[token].js
- pages/reset-password/index.jsx
- utils/gqlMutations.js
This PR adds the forgot password functionality. It also adds a common graphql Mutations file.
> [AUTH] forgot password flow

- .gitignore
- components/upload/UploadApi.js
- pages/assets/[id].jsx
- pages/assets/index.jsx
Además, se elimina que los coja del localStorage. Issue #78
> feat: Se coge el usuario y el token del hook correspondiente

- components/upload/UploadApi.js
Para ello se ha utilizado una variable de entorno. Issue #87
> feat: Se cambia el endpoint por el del API Gateway

- pages/profile.jsx
This PR fixes the issues with the image upload on the profile.
> [AUTH] Fix image upload

- components/layout/Navbar.jsx
- styles/Navbar.module.css
There was an issue with the anchor links on the user menu that has been fixed.
> [AUTH] fix menu buttons

- components/auth/forms/SignupForm.js
- utils/gqlMutations.js
This PR auto-logins the user after creating an user
> [AUTH] change user flow

- components/layout/Footer.jsx
- components/layout/Layout.jsx
- utils/auth.js
This PR fixes the footer position, and it also fixes a bug when changing the profile picture
> [AUTH] fix footer
